_target_: datasets.droid.make_droid_dataset
name: droid

buffer_path: /tmp/weirdlab/zchuning/data/droid/buffer.zarr
shape_meta:
  # acceptable types: rgb, low_dim
  obs:
    # camera
    "exterior_image_1_left": &camera_meta
      shape: [180, 320, 3]
      type: rgb
    "exterior_image_2_left": *camera_meta
    "wrist_image_left": *camera_meta

    # lowdim
    "cartesian_position":
      shape: [6]
      type: low_dim
    "gripper_position":
      shape: [1]
      type: low_dim

  action:
    # 3(pos) + 6(rot) + 1(gripper)
    shape: [10]

seq_len: ${num_frames}
history_len: ${obs_num_frames}
normalize_action: True
normalize_lowdim: True
val_ratio: 0.05