_target_: datasets.utils.mixture.make_robot_video_mixture_dataset
name: libero_90_webvideo
shape_meta: &shape_meta
  obs:
    agentview_rgb: &camera_meta
      shape: [128, 128, 3]
      type: rgb
    eye_in_hand_rgb: *camera_meta
  action:
    shape: [7] # pos + quarternion + gripper
hdf5_path_globs: &hdf5_path_globs /home/ubuntu/LIBERO/libero/datasets/libero_90/*.hdf5
robot_train_val_sets:
  _target_: datasets.robomimic.make_robomimic_dataset
  name: libero_90
  hdf5_path_globs: *hdf5_path_globs
  buffer_path: /home/ubuntu/LIBERO/libero/datasets/libero_90/buffer.zarr
  shape_meta: *shape_meta
  seq_len: ${num_frames}
  val_ratio: 0.05
video_train_val_sets:
  _target_: datasets.webvideo.make_multiview_video_dataset
  name: webvideo
  index_paths: [
    /home/ubuntu/efs/chuning/k400_filtered.txt,
    /home/ubuntu/efs/chuning/ssv2_filtered.txt,
  ]
  shape_meta: *shape_meta
  seq_len: ${num_frames}
  obs_padding: "same"
  frame_skip: 2
  val_ratio: 0.05
balance_datasets: False