_target_: datasets.robomimic.make_robomimic_dataset
name: robomimic_transport_ph
hdf5_path_globs: /home/ubuntu/robomimic/datasets/transport/ph/image_v141.hdf5
buffer_path: /home/ubuntu/robomimic/datasets/transport/ph/image_v141.zarr
shape_meta:
  obs:
    shouldercamera0_image: &camera_meta
      shape: [84, 84, 3]
      type: rgb
    shouldercamera1_image: *camera_meta
    robot0_eye_in_hand_image: *camera_meta
    robot1_eye_in_hand_image: *camera_meta
  action:
    shape: [14] # 2 * (pos + quarternion + gripper)
seq_len: ${num_frames}
val_ratio: 0.05