defaults:
  - template_robomimic
  - _self_

name: robomimic_lift_ph
hdf5_path_globs: /home/zixuanh/unified-world-model/robomimic/datasets/lift/ph/image_v15.hdf5
buffer_path: /home/zixuanh/unified-world-model/robomimic/datasets/lift/ph/image_v15.zarr