_target_: datasets.robomimic.make_robomimic_dataset
name: robomimic_can_ph 
hdf5_path_globs: /home/ubuntu/robomimic/datasets/can/ph/image_v141.hdf5
buffer_path: /home/ubuntu/robomimic/datasets/can/ph/image_v141.zarr
shape_meta:
  obs:
    agentview_image: &camera_meta
      shape: [84, 84, 3]
      type: rgb
    robot0_eye_in_hand_image: *camera_meta
  action:
    shape: [7] # pos + quarternion + gripper
seq_len: ${num_frames}
val_ratio: 0.05