_target_: datasets.webvideo.make_multiview_video_dataset
name: webvideo_for_robomimic
index_paths: [
  /gscratch/weirdlab/zchuning/data/k400_filtered.txt,
  /gscratch/weirdlab/zchuning/data/ssv2_filtered.txt,
]
shape_meta:
  obs:
    agentview_image: &camera_meta
      shape: [84, 84, 3]
      type: rgb
    robot0_eye_in_hand_image: *camera_meta
  action:
    shape: [7] # pos + quarternion + gripper
seq_len: ${num_frames}
obs_padding: "same"
frame_skip: 2
val_ratio: 0.05
