defaults:
  - template_train_robomimic
  - _self_

pretrain_checkpoint_path: "/home/ubuntu/efs/chuning/logdir/${algo}/libero_90/benchmark/0/models.pt"
num_steps: 20000

clip_grad_norm: 1.0
scheduler:
  name: "cosine"
  num_training_steps: ${num_steps}
  num_warmup_steps: 1000