defaults:
  - template_train
  - _self_

pretrain_checkpoint_path: "logdir/${algo}/droid/benchmark/0/models.pt"
num_steps: 10000

clip_grad_norm: 1.0
scheduler:
  name: "cosine"
  num_training_steps: ${num_steps}
  num_warmup_steps: 1000